name: Java CI/CD with Gradle

on:
  push:
    branches: [ "dev", "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: pwd
      run: pwd

    - name: list files
      run: ls -al

    ## create OAuth2 setting file
    - name: make application.yml
      run: |
        ## create application.yml
        cd ./src/main
        touch ./application.yml
        echo "${{ secrets.ENV }}" >> ./application.yml
      shell: bash

    ## create database setting file
    - name: make application-database.yml
      run: |
        ## create application-database.yml
        cd ./src/main/resources
        touch ./application-database.yml
        echo "${{ secrets.DATABASE }}" >> ./application-database.yml
      shell: bash

    ## gradle build
    - name: Build with Gradle
      run: ./gradlew bootJar

    ## build and push web image
    - name: web) docker build and push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_REPO }}/astee-web .
        docker push ${{ secrets.DOCKER_REPO }}/astee-web

    ## docker compose up
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
          sudo docker rm -f $(docker ps -qa)
          sudo docker pull ${{ secrets.DOCKER_REPO }}/astee-web
          sudo docker pull ${{ secrets.DOCKER_REPO }}/astee-nginx
          docker-compose up -d
          docker image prune -f